### ISSUE TITLE
 ./main.rb:54: syntax error, unexpected ':', expecting ')' ...r_recent_media(user_id, count: 100, max_id: max_id)                               ^

### ISSUE THREAD

**Issue by h1rule** [ssjr/instagram_backup#1]
./main.rb:54: syntax error, unexpected ':', expecting ')'
...r_recent_media(user_id, count: 100, max_id: max_id)
                              ^

while trying to ./main.rb username

**Comment by ssjr** [comment]
which version of ruby?

**Comment by h1rule** [comment]
fixed with latest ruby version. thanks!
